In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.1.2'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)#Specific for numpy arrays

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)#More generalize way

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
arr2d = np.arange(0.0,12.0)

In [13]:
arr2d = arr2d.reshape(4,3)

In [14]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
x2 = torch.from_numpy(arr2d)

In [16]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [17]:
x2.dtype

torch.float64

In [18]:
#Relationship between original array and torch-version
arr[0] = 99 #We used .from_numpy in order to create a direct link
arr

array([99,  2,  3,  4,  5])

In [19]:
#If we do not want a direct link:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_tensor = torch.tensor(my_arr)

In [21]:
my_other_tensor = torch.from_numpy(my_arr)

In [22]:
my_tensor, my_other_tensor

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [23]:
my_arr[0] = 99

In [24]:
my_tensor, my_other_tensor #Affected the one created with .from_mupy or as_tensor methods

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32),
 tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32))

In [25]:
new_arr = np.array([1,2,3])

In [26]:
new_arr.dtype

dtype('int32')

In [27]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.Tensor(new_arr)#Floating point

tensor([1., 2., 3.])

In [29]:
torch.Tensor(new_arr).dtype

torch.float32

In [30]:
torch.FloatTensor(new_arr)#Same as Tensor

tensor([1., 2., 3.])

In [31]:
torch.FloatTensor(new_arr).dtype

torch.float32

In [35]:
torch.empty(2,2)

tensor([[3.6013e-43, 2.5000e+00],
        [0.0000e+00, 0.0000e+00]])

In [37]:
torch.zeros(4,3,dtype=torch.int32)#Floating by default

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [38]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [43]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [44]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [45]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [46]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [47]:
torch.rand(4,3)

tensor([[0.6775, 0.8394, 0.8705],
        [0.2617, 0.2257, 0.4136],
        [0.2144, 0.3363, 0.7041],
        [0.8081, 0.8821, 0.2327]])

In [48]:
torch.randn(4,3)

tensor([[ 0.4081,  0.6425, -0.9469],
        [-0.9197,  0.6558, -0.1288],
        [-0.1955,  0.3358,  0.4836],
        [-0.9555, -0.4165,  1.5439]])

In [49]:
torch.randint(0,10,(5,5))

tensor([[6, 3, 4, 4, 4],
        [1, 0, 7, 7, 4],
        [2, 1, 1, 3, 1],
        [6, 5, 4, 8, 0],
        [8, 7, 2, 7, 8]])

In [50]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [51]:
x.shape

torch.Size([2, 5])

In [52]:
torch.rand_like(x)

tensor([[0.4435, 0.5728, 0.6720, 0.0062, 0.1623],
        [0.5701, 0.1274, 0.9127, 0.8242, 0.9773]])

In [53]:
torch.randn_like(x)

tensor([[-1.6509,  1.1877,  1.0877, -1.0146,  2.1437],
        [ 1.9818,  1.7051,  1.6293, -0.6161,  0.3168]])

In [54]:
torch.randint_like(x,0,10)

tensor([[1., 5., 0., 6., 9.],
        [0., 3., 7., 9., 6.]])

In [56]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [57]:
x=torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [58]:
x[1,1]

tensor(3)

In [59]:
type(x[1,1])

torch.Tensor

In [60]:
x[:,1]

tensor([1, 3, 5])

In [62]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [63]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x.view(2,5)#Did not change original shape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [65]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x.reshape(2,5)#Difference?
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x.shape

torch.Size([10])

In [69]:
x.view(2,5)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [71]:
x[0] = 999
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [72]:
z #Has also changed with view on x

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [73]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x.shape

torch.Size([10])

In [76]:
x.view(2,-1) #Infered the 2nd dimension (has to make sense xD)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [77]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [78]:
a+b

tensor([5., 7., 9.])

In [79]:
torch.add(a,b)

tensor([5., 7., 9.])

In [81]:
a.mul(b), a

(tensor([ 4., 10., 18.]), tensor([1., 2., 3.]))

In [82]:
a.mul_(b), a #Reassign the result, same as a = a * b or a = a.mul(b)

(tensor([ 4., 10., 18.]), tensor([ 4., 10., 18.]))

In [83]:
a * b #Element wise operation

tensor([ 16.,  50., 108.])

In [84]:
a.mul(b)

tensor([ 16.,  50., 108.])

In [85]:
a.dot(b) #Dot product

tensor(174.)

In [86]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [87]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [88]:
a.shape

torch.Size([2, 3])

In [89]:
b.shape

torch.Size([3, 2])

In [90]:
torch.mm(a,b)#Matriz multiplication

tensor([[56, 62],
        [80, 89]])

In [91]:
a@b #Also matrix multiplication

tensor([[56, 62],
        [80, 89]])

In [92]:
x = torch.tensor([2.,3.,4.,5.])
x

tensor([2., 3., 4., 5.])

In [93]:
x.norm()

tensor(7.3485)

In [94]:
x.numel() #Number of elements, not size

4

In [95]:
len(x)

4